---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

   - name: Terminate instances
     ec2:
        state: 'absent'
        instance_ids: i-0a68276ecf0c69903
        region: us-east-1
